server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jhon29Z/config-service
          search-paths: config-data
  application:
    name: config-service